POST https://backend-fimqwb2tta-ez.a.run.app/passengers HTTP/1.1
content-type: application/json

{"name":"Nilgün","surname":"Türkmen", "location": "Bielefeld"}

###

GET http://localhost:3000/passengers/5ea70b28bbf7cb710503f2d4 HTTP/1.1

###
DELETE http://localhost:3000/passengers/5e9de11c0b0ac272d7866b1b HTTP/1.1

###

PATCH http://localhost:3000/passengers/663ca7b2c2f70d4de7f214c3 HTTP/1.1
content-type: application/json

{"name": "Yüksel", "location": "bielefeld"}

###

POST https://backend-fimqwb2tta-ez.a.run.app/drivers HTTP/1.1
content-type: application/json

{"name":"Lara","surname":"Arıer", "age": 18, "location": "Ankara"}

###
DELETE http://localhost:3000/drivers/5ea70bf063b0877147bd3e6b HTTP/1.1

###
POST http://localhost:3000/passengers/6640c5fb12738270beac7dbb/bookings HTTP/1.1
content-type: application/json

{"driverId": "664056e52d0d4e49d132b3d0", "origin": "Bielefeld", "destination": "Köln"}

###

PATCH http://localhost:3000/drivers/5ea70c8063b0877147bd3e6c HTTP/1.1
content-type: application/json

{"name": "a newer surname"}